Both Valid and InValid Test Case files added via upload
pds-data-dictionaries/ldd-proc pull request #28
Opened 2023-10-30 14:38 UTC by rsjoyner

## Summary

Enter summary here

## Test Data and/or Report

Enter info here

## Related Issues

Enter related issues here

2023-10-30 15:34 UTC, rsjoyner reviewed
Reviewed by de facto as I also created the test case files

2023-10-30 17:54 UTC, jordanpadams approved these changes

2023-10-30 17:58 UTC, jordanpadams requested changes

2023-10-30 17:58 UTC, jordanpadams commented on test/Product_DelimitedTable_INVALID_lid_ref_no-match.xml
> +        <information_model_version>1.20.0.0</information_model_version>
@rsjoyner per the [Regression Test Data Rules](https://pds-data-dictionaries.github.io/development/ldd-test.html?highlight=test#regression-test-data-rules), there are a few quirks to the system we need to keep in mind. Here are links to examples of what those rules are referring to:
* No schematron: https://github.com/pds-data-dictionaries/ldd-template/blob/main/test/test1_FAIL.xml#L3
* No schema location: https://github.com/pds-data-dictionaries/ldd-template/blob/main/test/test1_FAIL.xml#L10
* IM Version "variable": https://github.com/pds-data-dictionaries/ldd-template/blob/main/test/test1_FAIL.xml#L16

2023-11-02 23:05 UTC, jordanpadams commented
Closing for #29

2023-11-02 23:05 UTC, closed without merging